### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by Schiggebam** [Schiggebam/FightOfAIs3#17]
Kein Ton/ Sound im Spiel.
Fürs Erste, es wäre schon beim Klicken ein visuelles feedback zu bekommen.
Vielleicht auch ein Ton, wenn ein Kampf stattfindet oder man ein Gebäude anklickt.

**Comment by Ausfragezeichen** [comment]
Buildings finished: farm, field, barracs, camp1-3, hut
unit recruited, fight
background: wood, grass, stone, water
